#node index.js readpath --source="D:\temp\t1"
#node index.js pathsize --source="D:\temp\t1"
node index.js filesize --source="D:\temp\t1\(1972) Godzilla Vs Gigan.avi"
#node index.js filestats --source="D:\temp\t1\(1972) Godzilla Vs Gigan.avi"
#node index.js copyfile --source="D:\temp\t1\(1972) Godzilla Vs Gigan.avi" --target="D:\temp\t2\(1972) Godzilla Vs Gigan.avi"